#!/bin/sh
set -e

case "$1" in
    remove|deconfigure) ;;
    *) exit 0 ;;
esac

if [ -d /var/jb/usr/lib ]; then
    destination=/var/jb/Library/MobileSubstrate/DynamicLibraries
else
    destination=/Library/MobileSubstrate/DynamicLibraries
fi

rm -f "$destination/ArcLaunchGuestKeyboardBridge.dylib" "$destination/ArcLaunchGuestKeyboardBridge.plist"
